# Generated by Django 4.2.20 on 2026-04-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccounts', '0002_produceraccount_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_loyalty_points',
            field=models.IntegerField(default=0),
        ),
    ]
