# Generated by Django 4.2.29 on 2026-03-26 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserAccounts', '0001_initial'),
        ('ProducerProducts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserAccounts.produceraccount'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_allergens',
            field=models.ManyToManyField(to='ProducerProducts.allergen'),
        ),
    ]
