# Generated by Django 4.2.20 on 2026-04-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProducerProducts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
