# Generated by Django 4.2.20 on 2026-04-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserOrders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
