# Generated by Django 4.2.20 on 2026-04-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserOrders', '0002_order_order_type_order_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_type',
            new_name='delivery_order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.AddField(
            model_name='order',
            name='customer_delivery_address',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AddField(
            model_name='order',
            name='total_order_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='individal_item_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
