# Generated by Django 4.2.20 on 2026-04-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserOrders', '0003_rename_order_type_order_delivery_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='loyalty_points_earned',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
